### ISSUE TITLE
kylo ren hilt is bugged (hilts with more then 1 crystal)

### ISSUE THREAD

**Issue by NetFl3xx** [lightsaberplus/lite#2]
Hilts with more then one crystals (without Double blade) are broken. Like in the screenshot.

![Bild_2022-02-13_204820](https://user-images.githubusercontent.com/75414351/153772072-b2617a88-39e2-4816-ae4c-abbcd166178a.png)

**Comment by NetFl3xx** [comment]
![image](https://user-images.githubusercontent.com/75414351/153773483-21f0b955-7728-4135-9cad-a1a03d7fffe6.png)

**Comment by IbimsnicesYolo** [comment]
fixed
